#!/usr/local/bin/ansible-playbook
- name: '{{ name_vendor }} | Konductor | secrets.yml' 
  hosts: konductor
  vars_files:
    - '../cluster-vars.yml'
    - 'vars/global.yml'
  vars:
    module: "secrets"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  roles:
    - secrets
