#!/usr/local/bin/ansible-playbook

- name: ' Konductor UPI '
  hosts: konductor
  vars_files:
  - '../cluster-vars.yml'
  - 'vars/global.yml'
  - 'vars/{{ target_environment }}.yml'
# - 'vars/git.yml'
  vars:
    module: "build"
    state_provider: "local"
    tf_module_path: "{{ dir_terraform }}/shaman"
    vars_module_path: "{{ dir_terraform }}"
    ansible_name_module: " Konductor | UPI | {{ module }}"

  tasks:

    ####### Terraform Apply
    - name: '{{ ansible_name_module }} | terraform | apply'
      terraform:
        project_path: "{{ item }}"
        variables_file: "{{ vars_module_path }}/global.tfvars"
        state: present
      loop:
        - "{{ tf_module_path }}/elb"
        - "{{ tf_module_path }}/control-plane"
        - "{{ tf_module_path }}/route53"
      register: tf_output
