#!/usr/local/bin/ansible-playbook
- name: 'RedHat | Konductor | site.yml' 
  hosts: koffer

- import_playbook: tree.yml        # Create base deployment directory tree 
- import_playbook: ssl.yml         # Stage deployment secrets
- import_playbook: secrets.yml     # Stage deployment secrets
- import_playbook: templates.yml   # Template prerequisite configs & auxillary manifests 
- import_playbook: registry.yml    # Restart registry with new certificate
- import_playbook: manifests.yml   # Create & customize OpenShift manifest files
- import_playbook: ignition.yml    # Build RH CoreOS ignition files from manifests
- import_playbook: shaman.yml      # Build the ELB and OCP Control plane via Terraform
#- import_playbook: dns.yml         # Configure CoreDNS "BYO DNS" Deploy time NS
