---
- name: '{{ ansible_name_module }} | file | Create Directories' 
  file:
    mode: '0644'
    path: '{{ item }}'
    state: directory
  with_items:
    - '/root/.docker'
    - '{{ dir_platform }}/mirror'
    - '{{ dir_platform }}/secrets/registry/ssl'
    - '{{ dir_platform }}/secrets/registry/auth'
